language: php

php:
  - 7.3

addons:
  postgresql: "12.1"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php artisan key:generate
  - php artisan config:cache
  - ./vendor/phpunit/phpunit/phpunit tests
